name: CI

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - develop
    paths-ignore:
      - README.md
      - LICENSE

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app

jobs:
  test:
    runs-on: macos-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # ビルド
    - name: Xcode build
      run: make build-debug

    # 単体テストの実行
    - name: Xcode test
      run: make test

  info:
    runs-on: macos-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # 端末の一覧出力
    - name: Show devices
      run: make show-devices
